/**
 * Maps Skype emoji shortcodes to their Unicode emoji equivalents.
 * Handles both XML tags (<ss type="smile">) and shorthand notation ((smile)).
 */
const skypeEmojiMap: Record<string, string> = {
  smile: "😊",
  sadsmile: "🙁",
  bigsmile: "😃",
  cool: "😎",
  wink: "😉",
  crying: "😢",
  sweat: "😓",
  speechless: "😶",
  kiss: "😘",
  kissingfacewithsmilingeyes: "😙",
  "1f619_kissingfacewithsmilingeyes": "😙",
  tongueout: "😛",
  blush: "😊",
  wonder: "😕",
  sleepy: "😴",
  dull: "😒",
  inlove: "😍",
  evilgrin: "😈",
  talking: "🗣️",
  yawn: "🥱",
  puke: "🤮",
  doh: "🤦",
  angry: "😠",
  wasntme: "🤷",
  party: "🥳",
  worried: "😟",
  mmm: "😋",
  nerd: "🤓",
  lipssealed: "🤐",
  devil: "😈",
  angel: "😇",
  envy: "😒",
  makeup: "💄",
  think: "🤔",
  rofl: "🤣",
  happy: "😊",
  smirk: "😏",
  emo: "😔",
  surprise: "😲",
  swear: "🤬",
  giggle: "😆",
  wondering: "🤔",
  sleepless: "😫",
  snooze: "😴",
  sick: "🤒",
  sweating: "😰",
  smiling: "😊",
  grinning: "😁",
  fearful: "😨",
  relieved: "😌",
  triumph: "😤",
  unamused: "😑",
  facepalm: "🤦",
  shrug: "🤷",
  fubar: "😵",
  inpain: "😣",
  bandit: "😎",
  confident: "😎",
  confidential: "🤐",
  malthe: "😄",
  nerdy: "🤓",
  oliver: "😊",
  selfie: "🤳",
  toivo: "😄",
  lol: "😂",
  sob: "😭",
  loudlycrying: "😭",
  joy: "😂",
  grin: "😁",
  stuck: "😛",
  sunglasses: "😎",
  neutral: "😐",
  nomouth: "😶",
  innocent: "😇",
  smileeyes: "😊",
  smilingeyes: "😊",
  relaxed: "☺️",
  yum: "😋",
  drunk: "🥴",
  facewithmonocle: "🧐",
  mindblown: "🤯",
  kissingclosedeyes: "😚",
  smilingfacewithtear: "🥲",
  pleadingface: "🥺",
  disguisedface: "🥸",
  partyingface: "🥳",
  woozyface: "🥴",
  dottedlineface: "🫥",
  facewithdiagonalmouth: "🫤",
  shakingface: "🫨",
  smilingfacewithhalo: "😇",
  smilingfacewithhorns: "😈",
  skull: "💀",
  skullandcrossbones: "☠️",

  hi: "👋",
  wave: "👋",
  bye: "👋",
  clap: "👏",
  bow: "🙇",
  pray: "🙏",
  rock: "🤘",
  muscle: "💪",
  handshake: "🤝",
  nod: "👍",
  shake: "👎",
  yes: "✔️",
  no: "❌",
  talktothehand: "🖐️",
  finger: "☝️",
  pointupindex: "☝️",
  fingers: "🤞",
  highfive: "🙌",
  ok: "👌",
  punch: "👊",
  victory: "✌️",
  thumbsup: "👍",
  thumbsdown: "👎",
  thumbs: "👍",
  fist: "👊",
  v: "✌️",
  raised: "✋",
  raisedhand: "✋",
  raisedback: "🤚",
  vulcan: "🖖",
  middlefinger: "🖕",
  headbang: "🤘",
  flex: "💪",

  womanartist: "👩‍🎨",

  heart: "❤️",
  brokenheart: "💔",
  hearthands: "🫶",
  love: "😍",
  lips: "👄",
  hug: "🤗",
  kissmark: "💋",
  hearteyes: "😍",
  heartkiss: "😘",

  dog: "🐕",
  cat: "🐈",
  penguin: "🐧",
  penguinkiss: "🐧😘",
  panda: "🐼",
  monkey: "🐵",
  hedgehog: "🦔",
  llama: "🦙",
  sheep: "🐑",
  pig: "🐷",
  flower: "🌸",
  sun: "☀️",
  moon: "🌙",
  star: "⭐",
  rain: "🌧️",
  rainbow: "🌈",
  cloud: "☁️",
  lightning: "⚡",
  snowflake: "❄️",
  fire: "🔥",
  nazar: "🧿",
  sparkles: "✨",

  coffee: "☕",
  pizza: "🍕",
  cake: "🎂",
  beer: "🍺",
  drink: "🍹",
  wine: "🍷",

  gift: "🎁",
  camera: "📷",
  phone: "📱",
  call: "📞",
  plane: "✈️",
  car: "🚗",
  bike: "🚴",
  computer: "💻",
  tv: "📺",
  movie: "🎬",
  music: "🎵",
  football: "⚽",
  basketball: "🏀",
  soccer: "⚽",
  tennis: "🎾",
  trophy: "🏆",
  winner: "🏆",
  celebrate: "🎉",
  partypopper: "🎉",
  congrats: "🎊",
  birthday: "🎂",
  fireworks: "🎆",
  balloon: "🎈",
  mail: "✉️",
  time: "⏰",
  clock: "⏰",
  umbrella: "☂️",
  island: "🏝️",
  flag: "🚩",
  poolparty: "🏊",
  skipping: "🦘",
  skip: "⏭️",
  bricklayers: "🧱",
  neil: "👨",

  bomb: "💣",
  zzz: "💤",
  boom: "💥",
  sweatdrops: "💦",
  dash: "💨",
  poop: "💩",
  tongue: "👅",
  ear: "👂",
  nose: "👃",
  eye: "👁️",
  eyes: "👀",
  "1f440_eyes": "👀",
  bust: "👤",
  busts: "👥",
  speech: "💬",
  footprints: "👣",
  cash: "💰",
  idea: "💡",
  dont: "🚫",
  hear: "👂",
  laugh: "😂",
  mooning: "🍑",
  tmi: "🙈",
  waiting: "⏳",
  holdon: "✋",
  mytime: "⏰",
  myspace: "🌐",
  lalala: "🎵",
  talk: "💬",
  thinking: "🤔",
  listening: "👂",
  smoking: "🚬",
  smoke: "🚬",
  skype: "☁️",
  mediumwhitesquare: "◻️",

  ":)": "😊",
  ":(": "🙁",
  ":d": "😃",
  ":p": "😛",
  ";)": "😉",
  ":o": "😮",
  ":'(": "😢",
  ":|": "😐",
  ":*": "😘",
  ":x": "😙",
  ">:)": "😈",
  "<3": "❤️",
  "</3": "💔",
  ":3": "😙",
  ":@": "😠",
  "^_^": "😊",
  "-_-": "😑",
  o_o: "😳",
  "<o>": "👼",

  d: "😃",
  p: "😛",
  o: "😮",
  s: "😕",
  x: "🤐",
  "8": "😎",
  "|": "😐",
  "*": "😘",
  "@": "😠",
  "^": "😊",
};

const emojiPatterns: Array<[RegExp, string]> = Object.keys(skypeEmojiMap)
  .sort((a, b) => b.length - a.length)
  .map((key) => [
    new RegExp(`\\(${key.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\\)`, "gi"),
    skypeEmojiMap[key],
  ]);

const ssTagPattern =
  /<ss[^>]*type="([^"]+)"[^>]*>[\s\S]*?<\/ss>/gi;

export function parseSkypeEmoji(text: string): string {
  if (!text) return text;

  let parsed = text.replace(ssTagPattern, (_, rawType) => {
    const type = (rawType ?? "").toLowerCase();
    return skypeEmojiMap[type] || "";
  });

  if (parsed.indexOf("(") === -1) {
    return parsed;
  }

  for (const [pattern, emoji] of emojiPatterns) {
    parsed = parsed.replace(pattern, emoji);
  }
  return parsed;
}
